title: Xodus-DNQ
description: Kotlin library for the data definition and queries over Xodus.
version: 1.0.173
github:
  repo: https://github.com/JetBrains/xodus-dnq

toc:
  - index.md
  - use-in-your-project.md
  - persistent-class.md
  - properties.md
  - queries.md
  - meta-model.md
  - sample.md

plugins:
  - jekyll-sitemap